FROM python:3.6

WORKDIR /usr/src/app

COPY static ./static
COPY templates ./templates
COPY requirements.txt ./ 
COPY main.py ./
COPY config_file.cfg  ./
RUN pip install --no-cache-dir -r requirements.txt

CMD [ "python", "./main.py" ]