# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mysql:
  persistence:
    enabled: true
    storageClass: default
    accessMode: ReadWriteOnce
    size: 3Gi
    annotations: {}

  initializationFiles: 
    first-db.sql: |-
      CREATE DATABASE IF NOT EXISTS `votingdb`;
      USE votingdb;
      CREATE USER 'votinguser'@'%' IDENTIFIED BY 'WeLcOmE123';
      GRANT ALL PRIVILEGES ON *.* TO 'votinguser'@'%';
      GRANT ALL PRIVILEGES ON `votingdb`.* TO 'votinguser'@'%';
      CREATE TABLE `votingtable` (`votevalue` varchar(128)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  image: "mysql"
  imageTag: "mysql-5.7"
  mysqlRootPassword: WeLcOmE123
  imagePullPolicy: Always
  name: mysql
voting:
  replicaCount: 1
  image: "voting"
  imageTag: "voting-0.1"
  imagePullPolicy: Always
  name: voting
ingress_controller:
  external: false
  service:
    create: true
    externalIPs: [10.240.0.10]
    httpPort:
      enable: false
      nodePort: 30100
      port: 80
      targetPort: 80
    httpsPort:
      enable: true
      nodePort: 30101
      port: 443
      targetPort: 443
    loadBalancerIP: '40.71.238.9'
    loadBalancerSourceRanges: []
    name: ingress-nginx
    type: LoadBalancer
imageVersions:
  ingress_controller: nginx-3.0.0-1
  mysql: mysql-5.7
global:
  ingress_controller:
    create: true
  registry:
    server: attbpa.azurecr.io
registry:
  password: 04xQyCfuOKfhWdFQsLhaHIlnZymh/AAU
  username: attbpa
k8sdashboard:
  create: false
  imageVersions:
    k8sdashboard: v2.0.0-beta1
    metricsscraper: metrics-scraper-v1.0.0
  nodePort:
    https: 30801
 