{{- if .Values.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bpa.fullname" . }}-dcr
  labels:
    app: {{ template "bpa.name" . }}
    chart: {{ template "bpa.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}