apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.voting.name }}
  labels:
    app: {{ .Values.voting.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.voting.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.voting.name }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.global.registry }}
      imagePullSecrets:
        - name: {{ template "bpa.fullname" . }}-dcr
      {{- end }}
      containers:
        - name: voting
          image: {{ template "imageRegistryUrl" . }}/{{ .Values.voting.image }}:{{ .Values.voting.imageTag }}
          imagePullPolicy: {{ .Values.voting.imagePullPolicy }}
          args:
            - '--bind'
            - '0.0.0.0'
            - 'app:app'
          ports:
            - name: gunicorn
              containerPort: 5000
          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - /bin/sh
                - -c 
                - "pidof -x gunicorn"
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 5000
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.voting.name }}
  labels:
    app: {{ .Values.voting.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: {{ .Values.voting.name }}
  selector:
    app: {{ .Values.voting.name }}
    release: {{ .Release.Name }}

