apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ values.voting.name }}
  labels:
    app: {{ values.voting.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ values.voting.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.voting.imagePullPolicy }}
          env:
          - name: PORT
            value: 5000
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ values.voting.name }}
  labels:
    app: {{ values.voting.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: {{ .Values.voting.name }}
  selector:
    app: {{ values.voting.name }}
    release: {{ .Release.Name }}

