apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.voting.name }}
  labels:
    app: {{ .Values.voting.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: voting
      app.kubernetes.io/part-of: voting
  template:
    metadata:
      labels:
        app: {{ .Values.voting.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: voting
          image: {{ template "imageRegistryUrl" . }}/{{ .Values.voting.image }}:{{ .Values.voting.imageTag }}
          imagePullPolicy: {{ .Values.voting.imagePullPolicy }}
          env:
          - name: PORT
            value: 5000
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.voting.name }}
  labels:
    app: {{ .Values.voting.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: {{ .Values.voting.name }}
  selector:
    app: {{ .Values.voting.name }}
    release: {{ .Release.Name }}

